@startuml

class Juego {
  - puntuacion : int
  + PruebaJuego()
  + getPuntuacion() : int
  + sumarPuntos(puntos: int) : boolean
}

class PruebaJuego {
  + main(args: String[]) : void
}

Juego --> PruebaJuego

@enduml
