@startuml

class Descuento{
+ producto : String
+ precio : double
+ porcentaje : int
+ Descuento(producto: string, precio: Double, porcentaje : int)
+ calcularDescuento(): void
}

object Producto1{
+ producto = "Cola"
+ precio = 10
+ porcentaje = 2%
}
object Producto2{
+ producto = "Atun"
+ precio = 2,35
+ porcentaje = 5%
}
object Producto3{
+ producto = "Telefono"
+ precio = 185,3
+ porcentaje = 12%
}

Descuento -- Producto1
Descuento -- Producto2
Descuento -- Producto3


@enduml