@startuml
Usuario --> Eduardo

class Usuario {
    String nombre
    public static String saludar(String nombre) {
 }

class Eduardo {
    Usuario
    String saludo = Usuario.saludar(nombreUsuario)
 }
@enduml